### ISSUE TITLE
streaming not working in https://dash-gallery.plotly.host/dash-wind-streaming/ 

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-sample-apps#331]
# App name
dash-wind-streaming
# Description of bug
blank charts - no streaming 
# How to replicate the bug
visit deployed app: https://dash-gallery.plotly.host/dash-wind-streaming/

**Comment by rpkyle** [comment]
@shammamah It's possible @CanerIrfanoglu might be able to help resolve this one once he's finished tackling updates to the brain surface viewer application.

**Comment by michaelbabyn** [comment]
@shammamah , I looked into this one and I think we can really speed things up by replacing plotly.py `graph_objects` with dicts since most of the app's cpu cycles were spent validating the updated graphs. I don't really know how this repo flows but I made a PR that will merge into the `dash-wind-streaming` branch in #332 that does that.
