### ISSUE TITLE
Circos app not showing Circos plot

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/dash-sample-apps#362]
# App name
Circos
# Description of bug
Circos plot doesn't often render, when it did it only rendered half a circle 
# How to replicate the bug
Open the app, see no plot
# Other notes
I'd expect to see the circos plot right away

**Comment by christopherjeon** [comment]
I'm currently looking into this bug - this app was made over a year ago and there's a lot to go through. I think I may have to re-wire these callback functions one by one (possibility that there may be a race condition somewhere?) I'll keep working on this and re-convene with @lundstrj next Monday. 

For the time being, I am going to remove this app from the gallery because it's best not to show a faulty app to customers.

**Comment by christopherjeon** [comment]
The bug has been fixed - here is the PR: https://github.com/plotly/dash-bio/pull/476

@lundstrj I'm not sure if this bug should be addressed in the documentation?

**Comment by lundstrj** [comment]
If it is an unknown behavior and we intend to keep it around for a while, then yes, we should document it.

**Comment by christopherjeon** [comment]
Since this PR has been merged, I will close this issue. I've created an issue post on the Dash repo (https://github.com/plotly/dash/issues/1105)and there will be another corresponding on the Dash Bio repo.
