### ISSUE TITLE
Add GTM tags to DashR apps

### ISSUE THREAD

**Issue by HammadTheOne** [plotly/dash-sample-apps#395]
Currently two DashR apps `Dashr-NCBI-Explorer` and `Dashr-Uber-Rasterizer` don't have GTM analytics scripts in their index headers.  

This is expected to be done with the release of Dash for R 0.3.0 in the near future which will include the `index_customization` feature that makes this possible. At that point I can update the apps and redeploy them to the gallery with the included tags. 

@ycaokris

**Comment by HammadTheOne** [comment]
Updated the `dashr-uber-rasterizer` and `dashr-ncbi-explorer` apps with the GTM script. Will close this issue once it's confirmed that it's successfully triggering.

**Comment by ycaokris** [comment]
@HammadTheOne thanks!

Looked like index string works as I could see `nostring` tag in the beginning of `body`. 

Just noticed from rasterizer-demo :  

The GTM js script is embedded in `assets/` folder as a GA.js and that's why we see it in the footer, is it possible to add it inside index string as well so that it get passed into `header`?

As per requirement in https://github.com/plotly/dash-sample-apps/issues/343#issue-514105869. Here's what we did for python apps by editing `app.index_string` prior to fire the `__main__`

https://github.com/plotly/dash-sample-apps/blob/854b8df105e24b04f6b3f9124c016f1e01b23691/predeploy.py#L5-L28<img width="581" alt="Screen Shot 2020-02-18 at 11 20 42 AM" src="https://user-images.githubusercontent.com/35306149/74764674-22a01800-5250-11ea-9523-5a8cc046202a.png">

**Comment by HammadTheOne** [comment]
@ycaokris 

I updated the NCBI Explorer one here: https://dash-gallery.plotly.host/dashr-ncbi-explorer/

I should be correctly placed now, I moved the script from assets directly into the `index_string` and it should be in the header now.

**Comment by ycaokris** [comment]
Looks good 💃 Thanks @HammadTheOne

**Comment by HammadTheOne** [comment]
#343 has been closed, closing this one as well now that we know it's included. Thanks for your help with this @ycaokris!
