### ISSUE TITLE
Can the template or source code be shared 

### ISSUE THREAD

**Issue by UGuntupalli** [plotly/dash-sample-apps#665]
Hello, 
       I really like the features shown in the gallery example(s) of some Dash apps. I could not find the source code for it, can it be kindly shared: 
  

1. https://dash-gallery.plotly.host/ddk-clinical-trial-dashboard/

2. https://dash-gallery.plotly.host/transport-routes-analysis/

Thanks 
Uday

**Comment by xhlulu** [comment]
Please see the [description of the app on the portal](https://dash-gallery.plotly.host/Portal/?search=clinical%20trial)

**Comment by UGuntupalli** [comment]
@xhlulu , 
       Are you essentially saying these are not publicly available ? 

Thanks 
Uday

**Comment by xhlulu** [comment]
If the source code is not in this repo then it's likely an app that uses licensed products, which is why the code is not publicly accessible. 

We are working on adding tags that clearly differentiate open sourced apps from ddk so it's easier to navigate if you are interested solely on open source apps. But in general you can read the description of the app you are interested in to know if it uses licensed products or not.

**Comment by UGuntupalli** [comment]
Thank you for the clarification. Appreciate it.
